### PR TITLE
Manually upgrade 0.1.3 -> to 0.1.4

### PR DESCRIPTION
**Pull request by sahiljhawar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@sahiljhawar So after you merge this, then you will revert the yaml to the syntax they had before for future pypi uploads?

**Comment by sahiljhawar** [comment]
Yes, I think so. By the next release if our PyPi size limit is not increased we can still use the same config. Only caveat is, we have to do it manually.

**Comment by sahiljhawar** [comment]
I am not sure what is going wrong. But here are my assumptions/observations:

-  When rendering using `conda-smithy`, it checks for the `conda-smithy` version and then only renders the package. Since `conda-smity 3.31.0` is in broken state right now it cannot be installed from `conda`. I tried installing from source but that also didn't work. Therefore I installed `conda-smithy` in 'broken' state (conda install conda-forge/label/main::conda-smithy) and used it to render and it worked fine (didn't raise any error).

- We can see obvious changes in the new scripts, but I believe there is more to the broken `smithy`. I reverted the build scripts to previous version but the CI again failed, maybe the changes in the scripts are needed by `smithy 3.31.0`.

I will wait for some more time; until there's some fix by the `smithy` team. However, in the mean time if you get a solution please push it.

**Comment by sahiljhawar** [comment]
@conda-forge-admin, please rerender

**Comment by sahiljhawar** [comment]
@conda-forge-admin, please rerender

**Comment by sahiljhawar** [comment]
@conda-forge/core Hi again, I have tried multiple times (on local) but the pipeline never passes. I am assuming the root cause is `ClobberWarning` and I have tried to change the Python versions but the error still remains. Can you please help in fixing this? Am I missing something?

**Comment by hmaarrfk** [comment]
I think you should have a section in your pyproject.toml 

called

tool.setuptools

see maybe 

https://github.com/hhatto/autopep8/blob/af7399d90926f2fe99a71f15197a08fa197f73a1/pyproject.toml#L44

**Comment by sahiljhawar** [comment]
@hmaarrfk We already have that: https://github.com/nuclear-multimessenger-astronomy/nmma/blob/25fe95e955efca90b8decdca89e5afb2406cafa7/pyproject.toml#L75

**Comment by hmaarrfk** [comment]
Try;

```
[tool.setuptools.packages.find]
include = ["nmma*"]
```

it seems like it isn't searching through subdirectories. I haven't been too fond of the pyproject.toml transition and avoided it in my projects, but the `pip` command isn't finding the subdirectories with the syntax you chose.

**Comment by sahiljhawar** [comment]
But we already had 3-4 conda releases with pyproject.toml and went fine

**Comment by mcoughlin** [comment]
@sahiljhawar Is this a case where a 0.1.5 release would alleviate these issues?

**Comment by hmaarrfk** [comment]
> But we already had 3-4 conda releases with pyproject.toml and went fine

If you have a linux machine, try to do:

```
python build-locally.py --debug 
```
then activate the environment, and edit things until you see that the whole subdirectories are installed correctly. That is what  I did and found that the proposed changes to the pyproject.toml worked.

As I said, I had a really rough time with the pyproject.toml transition and this is par for the course.

**Comment by sahiljhawar** [comment]
@mcoughlin Can't say for sure. I can try implementing Mark's suggestion and if it works maybe a 0.1.5 or uploading that local build on anaconda (if is't possible).

**Comment by sahiljhawar** [comment]
@hmaarrfk I am using Github codespaces to test this out as it allows for a clean base environment (0 chances of any conflicts).

**Comment by hmaarrfk** [comment]
For your reference build locally uses docker to also create the same build environment. Good luck

**Comment by sahiljhawar** [comment]
Thanks @hmaarrfk. Your code snippet worked. Looks like since we changed some configuration in the `pyproject.toml` it was not working well with the conda build process

**Comment by sahiljhawar** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
